### ISSUE TITLE
Improve usability of the migrate command

### ISSUE THREAD

**Issue by alejdg** [canonical/jimm#1371]
In the [migrate your model doc](https://canonical-jaas-documentation.readthedocs-hosted.com/en/latest/how-to/migrate_models_internal/#migrate-your-model) it is stated:
>The following command will migrate a model named my-model to the desired controller, in this case called my-controller.
>
>```
>MODEL_NAME=my-model
>MODEL_UUID=$(juju show-model $MODEL_NAME --format yaml | yq .$MODEL_NAME.model-uuid)
>jimmctl migrate my-controller $MODEL_UUID
>```

The user shouldn't need to run a juju command to get the the model UID to use that in a jimmctl command. To improve the usability, `jimmctl` should be able to do `jimmctl migrate my-controller my-model`.

If there's ambiguity in the `my-model` name since there could be models with the same name but in different controllers, jimm should require a unique identifier like <controller-name>.<model-name>.

**Comment by ale8k** [comment]
This is doable, going to triage. 

My suggestion: Use model names and resolve UUID internally.
