### ISSUE TITLE
Improve `jimmctl migrate` command grammar

### ISSUE THREAD

**Issue by alejdg** [canonical/jimm#1372]
[enhancement]
The command to migrate a model, `jimmctl migrate my-controller $MODEL_UUID`, is grammatically incorrect and makes it harder to understand it. 

The structure should be *Subject -> Verb -> Object -> Adverb*, i.e: `"JIMM migrates Something Somewhere"`. Example: `jimmctl migrate $MODEL_UUID my-controller`

**Comment by ale8k** [comment]
We are currently working on the UX of jimmctl commands and this will likely be addressed as a result of that process. Closing until then.
