### ISSUE TITLE
ReBAC: User's group names are ids

### ISSUE THREAD

**Issue by huwshimi** [canonical/jimm#1418]
In the response for a user's groups: `/identities/{id}/groups` the name value contains the id:

```json
{
    "_links": {
        "next": {
            "href": ""
        }
    },
    "_meta": {
        "pageToken": "",
        "size": 1
    },
    "data": [
        {
            "id": "a084509c-33c8-4ec7-b46c-d0f74958f892",
            "name": "a084509c-33c8-4ec7-b46c-d0f74958f892"
        }
    ],
    "message": "",
    "status": 200
}
```

The same group from the `/groups` response is:

```
{
    "_links": {
        "next": {
            "href": "/rebac/v1/groups?page=1"
        }
    },
    "_meta": {
        "page": 0,
        "size": 1,
        "total": 1
    },
    "data": [
        {
            "id": "a084509c-33c8-4ec7-b46c-d0f74958f892",
            "name": "group1"
        }
    ],
    "message": "",
    "status": 200
}
```

**Comment by kian99** [comment]
@huwshimi I've identified the issue, there is one problem with the solution, in an edge case it is possible that the OpenFGA tuple exists but the group has been removed from our database. This inconsistency will affect what we return in the response. At the moment I've opened #1422 with a fuller explanation of the various options. Feel free to chime in if you have an opinion on how we should handle the edge case.
