### ISSUE TITLE
ReBAC: Filter params ignored

### ISSUE THREAD

**Issue by huwshimi** [canonical/jimm#1421]
Filter params on ReBAC endpoints (`/groups?filter=test`, `/entitlements?filter=test`, `/identities?filter=test`) appear to be ignored.

**Comment by kian99** [comment]
It indeed seems we didn't implement filtering. Do you know if the filtering is supposed to be a fuzzy match or exact match? I'll need to take a look at the OpenAPI schema for the rebac-admin-ui to understand how it's intended to work.

**Comment by huwshimi** [comment]
@kian99 the way it works in the example app in https://github.com/canonical/rebac-admin-ui-handlers is a fuzzy match from memory.

**Comment by SimoneDutto** [comment]
Should be fixed now
